title: "Posts"
remote_theme: RMWinslow/just-the-docs-tweaked
search_enabled: false



gh_edit_link: false  # show or hide edit this page link


compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-feed
  - jekyll-seo-tag
